# Generated by Django 3.0.4 on 2020-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_interests_1', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty & Makeup', 'Beauty & Makeup'), ('Automobile', 'Automobile'), ('Arts', 'Arts'), ('Lifestyle', 'Lifestyle'), ('Music & dance', 'Music & dance'), ('Food & Beverages', 'Food & Beverages'), ('Movies & TV', 'Movies & TV'), ('Education & career', 'Education & career'), ('Business & Startup', 'Business & Startup'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Marketing & Social Media', 'Marketing & Social Media'), ('Fitness & Health', 'Fitness & Health'), ('Society & Politics', 'Society & Politics'), ('Photography', 'Photography')], max_length=255, null=True)),
                ('choose_interests_2', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty & Makeup', 'Beauty & Makeup'), ('Automobile', 'Automobile'), ('Arts', 'Arts'), ('Lifestyle', 'Lifestyle'), ('Music & dance', 'Music & dance'), ('Food & Beverages', 'Food & Beverages'), ('Movies & TV', 'Movies & TV'), ('Education & career', 'Education & career'), ('Business & Startup', 'Business & Startup'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Marketing & Social Media', 'Marketing & Social Media'), ('Fitness & Health', 'Fitness & Health'), ('Society & Politics', 'Society & Politics'), ('Photography', 'Photography')], max_length=255, null=True)),
                ('choose_interests_3', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty & Makeup', 'Beauty & Makeup'), ('Automobile', 'Automobile'), ('Arts', 'Arts'), ('Lifestyle', 'Lifestyle'), ('Music & dance', 'Music & dance'), ('Food & Beverages', 'Food & Beverages'), ('Movies & TV', 'Movies & TV'), ('Education & career', 'Education & career'), ('Business & Startup', 'Business & Startup'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Marketing & Social Media', 'Marketing & Social Media'), ('Fitness & Health', 'Fitness & Health'), ('Society & Politics', 'Society & Politics'), ('Photography', 'Photography')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_picture', models.ImageField(null=True, upload_to='', verbose_name='/media')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('your_role', models.CharField(choices=[('SOCIAL MEDIA STAR', 'SOCIAL MEDIA STAR'), ('MOM/DAD INFLUENCER', 'MOM/DAD INFLUENCER'), ('CAMPUS AMBASSADOR', 'CAMPUS AMBASSADOR'), ('WORKING PROFESSIONAL', 'WORKING PROFESSIONAL')], max_length=50, null=True)),
                ('agency_name', models.CharField(max_length=255, null=True)),
                ('agent_name', models.CharField(max_length=255, null=True)),
                ('agency_email', models.EmailField(max_length=254, null=True)),
                ('agent_number', models.IntegerField(null=True)),
                ('oldest_child', models.CharField(max_length=255, null=True)),
                ('youngest_child', models.CharField(max_length=255, null=True)),
                ('social_circle_friend', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('SOMEWHAT', 'SOMEWHAT')], max_length=10, null=True)),
                ('college_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('year_of_study', models.IntegerField(null=True)),
                ('chartbox_experience', models.CharField(max_length=3, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
