# Generated by Django 3.1 on 2020-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choose_interests",
                    models.CharField(
                        choices=[
                            ("Fashion", "Fashion"),
                            ("Beauty & Makeup", "Beauty & Makeup"),
                            ("Automobile", "Automobile"),
                            ("Arts", "Arts"),
                            ("Lifestyle", "Lifestyle"),
                            ("Music & dance", "Music & dance"),
                            ("Food & Beverages", "Food & Beverages"),
                            ("Movies & TV", "Movies & TV"),
                            ("Education & career", "Education & career"),
                            ("Business & Startup", "Business & Startup"),
                            ("Travel", "Travel"),
                            ("Technology", "Technology"),
                            ("Sports", "Sports"),
                            ("Marketing & Social Media", "Marketing & Social Media"),
                            ("Fitness & Health", "Fitness & Health"),
                            ("Society & Politics", "Society & Politics"),
                            ("Photography", "Photography"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "professional_picture",
                    models.ImageField(upload_to="", verbose_name="/media"),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                (
                    "your_role",
                    models.CharField(
                        choices=[
                            ("SOCIAL MEDIA STAR", "SOCIAL MEDIA STAR"),
                            ("MOM/DAD INFLUENCER", "MOM/DAD INFLUENCER"),
                            ("CAMPUS AMBASSADOR", "CAMPUS AMBASSADOR"),
                            ("WORKING PROFESSIONAL", "WORKING PROFESSIONAL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("agency_name", models.CharField(max_length=255)),
                ("agent_name", models.CharField(max_length=255)),
                ("agency_email", models.EmailField(max_length=254)),
                ("agent_number", models.IntegerField()),
                ("oldest_child", models.CharField(max_length=255)),
                ("youngest_child", models.CharField(max_length=255)),
                (
                    "social_circle_friend",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("NO", "NO"),
                            ("SOMEWHAT", "SOMEWHAT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("college_name", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                ("year_of_study", models.IntegerField()),
                ("chartbox_experience", models.CharField(max_length=3)),
                ("company_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
            ],
        ),
    ]
