# Generated by Django 3.1 on 2020-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interests",
            name="choose_interests",
            field=models.CharField(
                choices=[
                    ("Fashion", "Fashion"),
                    ("Beauty & Makeup", "Beauty & Makeup"),
                    ("Automobile", "Automobile"),
                    ("Arts", "Arts"),
                    ("Lifestyle", "Lifestyle"),
                    ("Music & dance", "Music & dance"),
                    ("Food & Beverages", "Food & Beverages"),
                    ("Movies & TV", "Movies & TV"),
                    ("Education & career", "Education & career"),
                    ("Business & Startup", "Business & Startup"),
                    ("Travel", "Travel"),
                    ("Technology", "Technology"),
                    ("Sports", "Sports"),
                    ("Marketing & Social Media", "Marketing & Social Media"),
                    ("Fitness & Health", "Fitness & Health"),
                    ("Society & Politics", "Society & Politics"),
                    ("Photography", "Photography"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="agency_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="agency_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="agent_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="agent_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="branch",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="chartbox_experience",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="college_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="designation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="district",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="oldest_child",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="professional_picture",
            field=models.ImageField(null=True, upload_to="", verbose_name="/media"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_circle_friend",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO"), ("SOMEWHAT", "SOMEWHAT")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="year_of_study",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="youngest_child",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="your_role",
            field=models.CharField(
                choices=[
                    ("SOCIAL MEDIA STAR", "SOCIAL MEDIA STAR"),
                    ("MOM/DAD INFLUENCER", "MOM/DAD INFLUENCER"),
                    ("CAMPUS AMBASSADOR", "CAMPUS AMBASSADOR"),
                    ("WORKING PROFESSIONAL", "WORKING PROFESSIONAL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
