# Generated by Django 3.1 on 2020-08-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20200825_2344'),
        ('UserProfile', '0004_auto_20200821_0239'),
    ]

    operations = [
    ]
